### ISSUE TITLE
Error when run Tcp.hs example code.

### ISSUE THREAD

**Issue by wpoosanguansit** [coot/free-algebras#9]
Hi,

I am trying out to see how the library works.  So I brought down the example code to run in stack lts-13.2 - ghc 8.6.2.  I am getting the error below:

error: Not in scope: type variable `msg'
204 | runTCP_IO sock = runTransportIO @(TcpMsg msg) sock . runTCP

Thanks for your help.

**Comment by coot** [comment]
The code compiles so I don't see how you got this error.  I never run the IO thing though, it's just an example, and you probably would need to finish it to have some working ping pong protocol over it.

**Comment by wpoosanguansit** [comment]
Thank you, Marcin.  I just took down the file and run within my setup.  Maybe if I have time, I will have to bring down your project to try out.  Thanks again for your help.
